spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tododb

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    lv.ctco.springboottemplate: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
